version: '3.8'
services:
  api_d2:
    container_name: api_da2
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - da2_database
    volumes:
      - .:/app
      - /app/node_modules
  da2_database:
    container_name: da2_database
    image: mysql:8.0.23
    platform: linux/x86_64
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_DB_PORT}:3306'
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data:
    name: da2-database-mysql-volume
